<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net462;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>13</LangVersion>
    <!--CS1591: Missing XML comment for publicly visible type or member-->
    <NoWarn>CS1591</NoWarn>
  </PropertyGroup>
  
  <!-- Package settings -->
  <PropertyGroup>
    <PackageId>Hangfire.Storage.MySql.Alu</PackageId>
    <PackageTags>hangfire;mysql</PackageTags>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Authors>Milosz Krajewski, Jan Janoušek</Authors>
    <Version>2.2.0-dev10</Version>
    <Description>Hangfire storage implementation for MySQL</Description>
    <RepositoryUrl>https://github.com/kfscz/Hangfire.Storage.MySql</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReleaseNotes>
      2.2.0-dev: Test build for .NET 8.0, removing dependecies and fixing tons of warnings.
      2.2.0-dev1: `MySqlFetchedJob` refactored to not use `Dapper`.
      2.2.0-dev2: `MySqlObjectsInstaller` refactored to not use `Dapper`.
      2.2.0-dev3: Removing dependency on `Dapper` from `CountersAggregator` and `MySqlJobQueue`.
      2.2.0-dev4: Removing dependency on `Dapper` from `MySqlJobQueueCountersAggregator`.
      2.2.0-dev5: Removing dependency on `Dapper` from `ResourceLock`.
      2.2.0-dev6: Refactoring `ResourceLock`
      2.2.0-dev7: Reduced dependency on `Dapper` in `MySqlMonitoringApi`. Optimalizer statistics gathering.
      2.2.0-dev8: BUGFIX: Fixed `MySqlObjectsInstaller`.
      2.2.0-dev9: BUGFIX: fixing generating SQL
      2.2.0-dev10: Timeline states refactored to not use `Dapper`
    </PackageReleaseNotes>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="Install.sql" />
    <EmbeddedResource Include="Migrations.xml" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Hangfire.Core" Version="[1.8.20, 2.0.0)" />
    <PackageReference Include="Dapper" Version="[2.0.30,)" />
    <PackageReference Include="System.ValueTuple" Version="4.6.1" Condition=" '$(TargetFramework)' == 'net462' " />
    <PackageReference Include="Nullable" Version="1.3.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  
</Project>